// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"登录","path":"/user/login","parentId":"1","id":"2"},"3":{"name":"注册","path":"/user/register","parentId":"1","id":"3"},"4":{"path":"/welcome","name":"欢迎","icon":"smile","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/admin","name":"管理页","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin","redirect":"/admin/user-manage","parentId":"5","id":"6"},"7":{"path":"/admin/sub-page","name":"二级管理页","parentId":"5","id":"7"},"8":{"path":"/admin/user-manage","name":"用户管理","parentId":"5","id":"8"},"9":{"name":"查询表格","icon":"table","path":"/list","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"*","layout":false,"id":"11"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'5': React.lazy(() => import( './EmptyRoute')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Admin__UserManage__index" */'@/pages/Admin/UserManage/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'10': React.lazy(() => import( './EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/macbook/Desktop/tmpFile/user-center/user-center-fronted/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
